In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import * 

In [4]:
d=pd.read_csv('heart-disease.csv')

'''
d=pd.read_csv('11zon_zip/heart-disease.csv')
 with pd.option_context('display.max_rows', None,
                           'display.max_columns', None,
                           'display.precision', 3,
                           ):print(d)
'''
d.isna().cumsum()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      0    0   0         0     0    0        0        0      0        0   
1      0    0   0         0     0    0        0        0      0        0   
2      0    0   0         0     0    0        0        0      0        0   
3      0    0   0         0     0    0        0        0      0        0   
4      0    0   0         0     0    0        0        0      0        0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298    0    0   0         0     0    0        0        0      0        0   
299    0    0   0         0     0    0        0        0      0        0   
300    0    0   0         0     0    0        0        0      0        0   
301    0    0   0         0     0    0        0        0      0        0   
302    0    0   0         0     0    0        0        0      0        0   

     slope  ca  thal  target  
0        0   0     0       0  
1        0   0     0       0  
2        0   0     0       0  
3        0   0     0       0  
4        0   0     0       0  
..     ...  ..   ...     ...  
298      0   0     0       0  
299      0   0     0       0  
300      0   0     0       0  
301      0   0     0       0  
302      0   0     0       0  

[303 rows x 14 columns]

In [5]:
                          

#features and matrix
x=d.drop('target',axis=1)
y=d['target']

In [6]:
import sklearn
xtr,xtst,ytr,ytst= sklearn.model_selection.train_test_split(x,y,test_size=0.2)

In [7]:
clf=sklearn.ensemble.RandomForestClassifier(n_estimators=23)


clf.fit(xtr,ytr)
 #model validate
clf.score(xtr,ytr)
 

1.0

In [8]:
print(clf.get_params())
result=clf.predict(xtst)
result 

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 23, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}


array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1])

In [9]:
import sklearn.metrics as est 

In [10]:
print(est.classification_report(ytst,result))

              precision    recall  f1-score   support

           0       0.87      0.83      0.85        24
           1       0.89      0.92      0.91        37

    accuracy                           0.89        61
   macro avg       0.88      0.88      0.88        61
weighted avg       0.88      0.89      0.88        61



In [9]:
# to find best params for estimators 
#use while or interation method by you

In [11]:
sklearn.metrics.accuracy_score(ytst,result)*100

88.52459016393442

In [12]:
clf.predict_proba(xtst)

array([[0.7826087 , 0.2173913 ],
       [0.91304348, 0.08695652],
       [0.13043478, 0.86956522],
       [0.95652174, 0.04347826],
       [0.95652174, 0.04347826],
       [0.13043478, 0.86956522],
       [0.7826087 , 0.2173913 ],
       [0.7826087 , 0.2173913 ],
       [0.43478261, 0.56521739],
       [0.60869565, 0.39130435],
       [0.43478261, 0.56521739],
       [0.86956522, 0.13043478],
       [0.56521739, 0.43478261],
       [0.        , 1.        ],
       [0.91304348, 0.08695652],
       [0.        , 1.        ],
       [0.52173913, 0.47826087],
       [0.82608696, 0.17391304],
       [0.26086957, 0.73913043],
       [0.08695652, 0.91304348],
       [0.39130435, 0.60869565],
       [0.26086957, 0.73913043],
       [0.52173913, 0.47826087],
       [0.17391304, 0.82608696],
       [0.17391304, 0.82608696],
       [0.2173913 , 0.7826087 ],
       [0.34782609, 0.65217391],
       [0.43478261, 0.56521739],
       [0.        , 1.        ],
       [0.69565217, 0.30434783],
       [0.

In [12]:
#save model
save=open('heart-disease-model.pkl','wb')
import pickle 
pickle.dump(clf,save)

In [13]:
#load a model
model_loaded=pickle.load(open('heart-disease-model.pkl','rb'))

In [16]:
model_loaded()  

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1], dtype=int64)